site_name: "Housing Library"

repo_url: https://github.com/hermangudjonson/housing.git

theme:
  name: "material"
  features:
    - navigation.instant
    - navigation.tabs

plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            docstring_section_style: list
            members_order: source
            summary: true
            show_if_no_docstring: true
            heading_level: 3
            separate_signature: true

nav:
  - Home: index.md
  - API Reference: reference/
