name: kaggle_gpu_v0
channels:
  - conda-forge
  - pytorch
  - nvidia
  - rapidsai
dependencies:
  - python =3.10
  - numpy =1.23.5
  - pandas =1.5.3
  - scipy =1.9.3
  - matplotlib =3.5.3
  - seaborn
  - pytorch
  - pyro-ppl
  - torchvision
  - torchaudio
  - python-wget
  - pandas-datareader
  - scikit-learn =1.3.1
  - cuml
  - cuda-version <=11.4
  - pandas-profiling =3.4
  - py-xgboost =1.7.1
  - catboost =1.1.1
  - optuna =3.3.0
  - optuna-dashboard
  - umap-learn
  - black
  - kaggle
  - fire
  - cloudpickle =2.2.1
  - mlflow =2.7.1
  - loguru
  - pip
  - pip:
    - sweetviz
    - lightgbm==4.0.0
    - /kaggle/input/housing-repo/housing-main