name: ml_v0_housing
channels:
  - conda-forge
  - pytorch
dependencies:
  - python =3.10
  - matplotlib
  - seaborn
  - pyobjc-core=8.2
  - jupyterlab
  - notebook
  - pytorch
  - pyro-ppl
  - torchvision
  - torchaudio
  - python-wget
  - pandas-datareader
  - scikit-learn
  - pandas-profiling =3.4
  - py-xgboost
  - lightgbm
  - catboost =1.1
  - optuna
  - optuna-dashboard
  - flaml[automl]
  - autogluon
  - shap
  - black
  - flit
  - kaggle
  - fire
  - cloudpickle
  - mlflow
  - pytest
  - pytest-cov
  - loguru
  - pre-commit
  - mkdocstrings-python
  - mkdocs-gen-files
  - mkdocs-literate-nav
  - mkdocs-material
  - pip
  - pip:
      - umap-learn[plot]
      - sweetviz
      - mkdocs-section-index
      - -e /Users/herman/Dropbox/ml_practice/classic_ml/housing/housing
